// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dots-and-boxes.proto

package dab;

public final class DotsAndBoxes {
  private DotsAndBoxes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameParameterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dab.GameParameter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 number_of_vertical_columns = 1;</code>
     * @return The numberOfVerticalColumns.
     */
    int getNumberOfVerticalColumns();

    /**
     * <code>uint32 number_of_horizontal_columns = 2;</code>
     * @return The numberOfHorizontalColumns.
     */
    int getNumberOfHorizontalColumns();
  }
  /**
   * Protobuf type {@code dab.GameParameter}
   */
  public static final class GameParameter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dab.GameParameter)
      GameParameterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameParameter.newBuilder() to construct.
    private GameParameter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameParameter() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameParameter();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameParameter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numberOfVerticalColumns_ = input.readUInt32();
              break;
            }
            case 16: {

              numberOfHorizontalColumns_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dab.DotsAndBoxes.internal_static_dab_GameParameter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dab.DotsAndBoxes.internal_static_dab_GameParameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dab.DotsAndBoxes.GameParameter.class, dab.DotsAndBoxes.GameParameter.Builder.class);
    }

    public static final int NUMBER_OF_VERTICAL_COLUMNS_FIELD_NUMBER = 1;
    private int numberOfVerticalColumns_;
    /**
     * <code>uint32 number_of_vertical_columns = 1;</code>
     * @return The numberOfVerticalColumns.
     */
    @java.lang.Override
    public int getNumberOfVerticalColumns() {
      return numberOfVerticalColumns_;
    }

    public static final int NUMBER_OF_HORIZONTAL_COLUMNS_FIELD_NUMBER = 2;
    private int numberOfHorizontalColumns_;
    /**
     * <code>uint32 number_of_horizontal_columns = 2;</code>
     * @return The numberOfHorizontalColumns.
     */
    @java.lang.Override
    public int getNumberOfHorizontalColumns() {
      return numberOfHorizontalColumns_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numberOfVerticalColumns_ != 0) {
        output.writeUInt32(1, numberOfVerticalColumns_);
      }
      if (numberOfHorizontalColumns_ != 0) {
        output.writeUInt32(2, numberOfHorizontalColumns_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numberOfVerticalColumns_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, numberOfVerticalColumns_);
      }
      if (numberOfHorizontalColumns_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, numberOfHorizontalColumns_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dab.DotsAndBoxes.GameParameter)) {
        return super.equals(obj);
      }
      dab.DotsAndBoxes.GameParameter other = (dab.DotsAndBoxes.GameParameter) obj;

      if (getNumberOfVerticalColumns()
          != other.getNumberOfVerticalColumns()) return false;
      if (getNumberOfHorizontalColumns()
          != other.getNumberOfHorizontalColumns()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_OF_VERTICAL_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfVerticalColumns();
      hash = (37 * hash) + NUMBER_OF_HORIZONTAL_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfHorizontalColumns();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dab.DotsAndBoxes.GameParameter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameParameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameParameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameParameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dab.DotsAndBoxes.GameParameter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dab.GameParameter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dab.GameParameter)
        dab.DotsAndBoxes.GameParameterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dab.DotsAndBoxes.internal_static_dab_GameParameter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dab.DotsAndBoxes.internal_static_dab_GameParameter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dab.DotsAndBoxes.GameParameter.class, dab.DotsAndBoxes.GameParameter.Builder.class);
      }

      // Construct using dab.DotsAndBoxes.GameParameter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numberOfVerticalColumns_ = 0;

        numberOfHorizontalColumns_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dab.DotsAndBoxes.internal_static_dab_GameParameter_descriptor;
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameParameter getDefaultInstanceForType() {
        return dab.DotsAndBoxes.GameParameter.getDefaultInstance();
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameParameter build() {
        dab.DotsAndBoxes.GameParameter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameParameter buildPartial() {
        dab.DotsAndBoxes.GameParameter result = new dab.DotsAndBoxes.GameParameter(this);
        result.numberOfVerticalColumns_ = numberOfVerticalColumns_;
        result.numberOfHorizontalColumns_ = numberOfHorizontalColumns_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dab.DotsAndBoxes.GameParameter) {
          return mergeFrom((dab.DotsAndBoxes.GameParameter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dab.DotsAndBoxes.GameParameter other) {
        if (other == dab.DotsAndBoxes.GameParameter.getDefaultInstance()) return this;
        if (other.getNumberOfVerticalColumns() != 0) {
          setNumberOfVerticalColumns(other.getNumberOfVerticalColumns());
        }
        if (other.getNumberOfHorizontalColumns() != 0) {
          setNumberOfHorizontalColumns(other.getNumberOfHorizontalColumns());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dab.DotsAndBoxes.GameParameter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dab.DotsAndBoxes.GameParameter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numberOfVerticalColumns_ ;
      /**
       * <code>uint32 number_of_vertical_columns = 1;</code>
       * @return The numberOfVerticalColumns.
       */
      @java.lang.Override
      public int getNumberOfVerticalColumns() {
        return numberOfVerticalColumns_;
      }
      /**
       * <code>uint32 number_of_vertical_columns = 1;</code>
       * @param value The numberOfVerticalColumns to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfVerticalColumns(int value) {
        
        numberOfVerticalColumns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_of_vertical_columns = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfVerticalColumns() {
        
        numberOfVerticalColumns_ = 0;
        onChanged();
        return this;
      }

      private int numberOfHorizontalColumns_ ;
      /**
       * <code>uint32 number_of_horizontal_columns = 2;</code>
       * @return The numberOfHorizontalColumns.
       */
      @java.lang.Override
      public int getNumberOfHorizontalColumns() {
        return numberOfHorizontalColumns_;
      }
      /**
       * <code>uint32 number_of_horizontal_columns = 2;</code>
       * @param value The numberOfHorizontalColumns to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfHorizontalColumns(int value) {
        
        numberOfHorizontalColumns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_of_horizontal_columns = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfHorizontalColumns() {
        
        numberOfHorizontalColumns_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dab.GameParameter)
    }

    // @@protoc_insertion_point(class_scope:dab.GameParameter)
    private static final dab.DotsAndBoxes.GameParameter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dab.DotsAndBoxes.GameParameter();
    }

    public static dab.DotsAndBoxes.GameParameter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameParameter>
        PARSER = new com.google.protobuf.AbstractParser<GameParameter>() {
      @java.lang.Override
      public GameParameter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameParameter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameParameter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameParameter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dab.DotsAndBoxes.GameParameter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameTurnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dab.GameTurn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool vertical = 1;</code>
     * @return The vertical.
     */
    boolean getVertical();

    /**
     * <code>uint32 target_column = 2;</code>
     * @return The targetColumn.
     */
    int getTargetColumn();

    /**
     * <code>uint32 target_gap = 3;</code>
     * @return The targetGap.
     */
    int getTargetGap();
  }
  /**
   * Protobuf type {@code dab.GameTurn}
   */
  public static final class GameTurn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dab.GameTurn)
      GameTurnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameTurn.newBuilder() to construct.
    private GameTurn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameTurn() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameTurn();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameTurn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              vertical_ = input.readBool();
              break;
            }
            case 16: {

              targetColumn_ = input.readUInt32();
              break;
            }
            case 24: {

              targetGap_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dab.DotsAndBoxes.internal_static_dab_GameTurn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dab.DotsAndBoxes.internal_static_dab_GameTurn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dab.DotsAndBoxes.GameTurn.class, dab.DotsAndBoxes.GameTurn.Builder.class);
    }

    public static final int VERTICAL_FIELD_NUMBER = 1;
    private boolean vertical_;
    /**
     * <code>bool vertical = 1;</code>
     * @return The vertical.
     */
    @java.lang.Override
    public boolean getVertical() {
      return vertical_;
    }

    public static final int TARGET_COLUMN_FIELD_NUMBER = 2;
    private int targetColumn_;
    /**
     * <code>uint32 target_column = 2;</code>
     * @return The targetColumn.
     */
    @java.lang.Override
    public int getTargetColumn() {
      return targetColumn_;
    }

    public static final int TARGET_GAP_FIELD_NUMBER = 3;
    private int targetGap_;
    /**
     * <code>uint32 target_gap = 3;</code>
     * @return The targetGap.
     */
    @java.lang.Override
    public int getTargetGap() {
      return targetGap_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vertical_ != false) {
        output.writeBool(1, vertical_);
      }
      if (targetColumn_ != 0) {
        output.writeUInt32(2, targetColumn_);
      }
      if (targetGap_ != 0) {
        output.writeUInt32(3, targetGap_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vertical_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, vertical_);
      }
      if (targetColumn_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, targetColumn_);
      }
      if (targetGap_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, targetGap_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dab.DotsAndBoxes.GameTurn)) {
        return super.equals(obj);
      }
      dab.DotsAndBoxes.GameTurn other = (dab.DotsAndBoxes.GameTurn) obj;

      if (getVertical()
          != other.getVertical()) return false;
      if (getTargetColumn()
          != other.getTargetColumn()) return false;
      if (getTargetGap()
          != other.getTargetGap()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERTICAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVertical());
      hash = (37 * hash) + TARGET_COLUMN_FIELD_NUMBER;
      hash = (53 * hash) + getTargetColumn();
      hash = (37 * hash) + TARGET_GAP_FIELD_NUMBER;
      hash = (53 * hash) + getTargetGap();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dab.DotsAndBoxes.GameTurn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameTurn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameTurn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameTurn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dab.DotsAndBoxes.GameTurn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dab.GameTurn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dab.GameTurn)
        dab.DotsAndBoxes.GameTurnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dab.DotsAndBoxes.internal_static_dab_GameTurn_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dab.DotsAndBoxes.internal_static_dab_GameTurn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dab.DotsAndBoxes.GameTurn.class, dab.DotsAndBoxes.GameTurn.Builder.class);
      }

      // Construct using dab.DotsAndBoxes.GameTurn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vertical_ = false;

        targetColumn_ = 0;

        targetGap_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dab.DotsAndBoxes.internal_static_dab_GameTurn_descriptor;
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameTurn getDefaultInstanceForType() {
        return dab.DotsAndBoxes.GameTurn.getDefaultInstance();
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameTurn build() {
        dab.DotsAndBoxes.GameTurn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameTurn buildPartial() {
        dab.DotsAndBoxes.GameTurn result = new dab.DotsAndBoxes.GameTurn(this);
        result.vertical_ = vertical_;
        result.targetColumn_ = targetColumn_;
        result.targetGap_ = targetGap_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dab.DotsAndBoxes.GameTurn) {
          return mergeFrom((dab.DotsAndBoxes.GameTurn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dab.DotsAndBoxes.GameTurn other) {
        if (other == dab.DotsAndBoxes.GameTurn.getDefaultInstance()) return this;
        if (other.getVertical() != false) {
          setVertical(other.getVertical());
        }
        if (other.getTargetColumn() != 0) {
          setTargetColumn(other.getTargetColumn());
        }
        if (other.getTargetGap() != 0) {
          setTargetGap(other.getTargetGap());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dab.DotsAndBoxes.GameTurn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dab.DotsAndBoxes.GameTurn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean vertical_ ;
      /**
       * <code>bool vertical = 1;</code>
       * @return The vertical.
       */
      @java.lang.Override
      public boolean getVertical() {
        return vertical_;
      }
      /**
       * <code>bool vertical = 1;</code>
       * @param value The vertical to set.
       * @return This builder for chaining.
       */
      public Builder setVertical(boolean value) {
        
        vertical_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool vertical = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVertical() {
        
        vertical_ = false;
        onChanged();
        return this;
      }

      private int targetColumn_ ;
      /**
       * <code>uint32 target_column = 2;</code>
       * @return The targetColumn.
       */
      @java.lang.Override
      public int getTargetColumn() {
        return targetColumn_;
      }
      /**
       * <code>uint32 target_column = 2;</code>
       * @param value The targetColumn to set.
       * @return This builder for chaining.
       */
      public Builder setTargetColumn(int value) {
        
        targetColumn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 target_column = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetColumn() {
        
        targetColumn_ = 0;
        onChanged();
        return this;
      }

      private int targetGap_ ;
      /**
       * <code>uint32 target_gap = 3;</code>
       * @return The targetGap.
       */
      @java.lang.Override
      public int getTargetGap() {
        return targetGap_;
      }
      /**
       * <code>uint32 target_gap = 3;</code>
       * @param value The targetGap to set.
       * @return This builder for chaining.
       */
      public Builder setTargetGap(int value) {
        
        targetGap_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 target_gap = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetGap() {
        
        targetGap_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dab.GameTurn)
    }

    // @@protoc_insertion_point(class_scope:dab.GameTurn)
    private static final dab.DotsAndBoxes.GameTurn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dab.DotsAndBoxes.GameTurn();
    }

    public static dab.DotsAndBoxes.GameTurn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameTurn>
        PARSER = new com.google.protobuf.AbstractParser<GameTurn>() {
      @java.lang.Override
      public GameTurn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameTurn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameTurn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameTurn> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dab.DotsAndBoxes.GameTurn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dab.GameState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 vertical_columns = 1;</code>
     * @return The verticalColumns.
     */
    int getVerticalColumns();

    /**
     * <code>uint32 horizontal_columns = 2;</code>
     * @return The horizontalColumns.
     */
    int getHorizontalColumns();

    /**
     * <code>bytes vertical_lines = 3;</code>
     * @return The verticalLines.
     */
    com.google.protobuf.ByteString getVerticalLines();

    /**
     * <code>bytes horizontal_lines = 4;</code>
     * @return The horizontalLines.
     */
    com.google.protobuf.ByteString getHorizontalLines();
  }
  /**
   * Protobuf type {@code dab.GameState}
   */
  public static final class GameState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dab.GameState)
      GameStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameState.newBuilder() to construct.
    private GameState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameState() {
      verticalLines_ = com.google.protobuf.ByteString.EMPTY;
      horizontalLines_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              verticalColumns_ = input.readUInt32();
              break;
            }
            case 16: {

              horizontalColumns_ = input.readUInt32();
              break;
            }
            case 26: {

              verticalLines_ = input.readBytes();
              break;
            }
            case 34: {

              horizontalLines_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dab.DotsAndBoxes.internal_static_dab_GameState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dab.DotsAndBoxes.internal_static_dab_GameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dab.DotsAndBoxes.GameState.class, dab.DotsAndBoxes.GameState.Builder.class);
    }

    public static final int VERTICAL_COLUMNS_FIELD_NUMBER = 1;
    private int verticalColumns_;
    /**
     * <code>uint32 vertical_columns = 1;</code>
     * @return The verticalColumns.
     */
    @java.lang.Override
    public int getVerticalColumns() {
      return verticalColumns_;
    }

    public static final int HORIZONTAL_COLUMNS_FIELD_NUMBER = 2;
    private int horizontalColumns_;
    /**
     * <code>uint32 horizontal_columns = 2;</code>
     * @return The horizontalColumns.
     */
    @java.lang.Override
    public int getHorizontalColumns() {
      return horizontalColumns_;
    }

    public static final int VERTICAL_LINES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString verticalLines_;
    /**
     * <code>bytes vertical_lines = 3;</code>
     * @return The verticalLines.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getVerticalLines() {
      return verticalLines_;
    }

    public static final int HORIZONTAL_LINES_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString horizontalLines_;
    /**
     * <code>bytes horizontal_lines = 4;</code>
     * @return The horizontalLines.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHorizontalLines() {
      return horizontalLines_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (verticalColumns_ != 0) {
        output.writeUInt32(1, verticalColumns_);
      }
      if (horizontalColumns_ != 0) {
        output.writeUInt32(2, horizontalColumns_);
      }
      if (!verticalLines_.isEmpty()) {
        output.writeBytes(3, verticalLines_);
      }
      if (!horizontalLines_.isEmpty()) {
        output.writeBytes(4, horizontalLines_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (verticalColumns_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, verticalColumns_);
      }
      if (horizontalColumns_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, horizontalColumns_);
      }
      if (!verticalLines_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, verticalLines_);
      }
      if (!horizontalLines_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, horizontalLines_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dab.DotsAndBoxes.GameState)) {
        return super.equals(obj);
      }
      dab.DotsAndBoxes.GameState other = (dab.DotsAndBoxes.GameState) obj;

      if (getVerticalColumns()
          != other.getVerticalColumns()) return false;
      if (getHorizontalColumns()
          != other.getHorizontalColumns()) return false;
      if (!getVerticalLines()
          .equals(other.getVerticalLines())) return false;
      if (!getHorizontalLines()
          .equals(other.getHorizontalLines())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERTICAL_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getVerticalColumns();
      hash = (37 * hash) + HORIZONTAL_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getHorizontalColumns();
      hash = (37 * hash) + VERTICAL_LINES_FIELD_NUMBER;
      hash = (53 * hash) + getVerticalLines().hashCode();
      hash = (37 * hash) + HORIZONTAL_LINES_FIELD_NUMBER;
      hash = (53 * hash) + getHorizontalLines().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dab.DotsAndBoxes.GameState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dab.DotsAndBoxes.GameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dab.DotsAndBoxes.GameState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dab.GameState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dab.GameState)
        dab.DotsAndBoxes.GameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dab.DotsAndBoxes.internal_static_dab_GameState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dab.DotsAndBoxes.internal_static_dab_GameState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dab.DotsAndBoxes.GameState.class, dab.DotsAndBoxes.GameState.Builder.class);
      }

      // Construct using dab.DotsAndBoxes.GameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        verticalColumns_ = 0;

        horizontalColumns_ = 0;

        verticalLines_ = com.google.protobuf.ByteString.EMPTY;

        horizontalLines_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dab.DotsAndBoxes.internal_static_dab_GameState_descriptor;
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameState getDefaultInstanceForType() {
        return dab.DotsAndBoxes.GameState.getDefaultInstance();
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameState build() {
        dab.DotsAndBoxes.GameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dab.DotsAndBoxes.GameState buildPartial() {
        dab.DotsAndBoxes.GameState result = new dab.DotsAndBoxes.GameState(this);
        result.verticalColumns_ = verticalColumns_;
        result.horizontalColumns_ = horizontalColumns_;
        result.verticalLines_ = verticalLines_;
        result.horizontalLines_ = horizontalLines_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dab.DotsAndBoxes.GameState) {
          return mergeFrom((dab.DotsAndBoxes.GameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dab.DotsAndBoxes.GameState other) {
        if (other == dab.DotsAndBoxes.GameState.getDefaultInstance()) return this;
        if (other.getVerticalColumns() != 0) {
          setVerticalColumns(other.getVerticalColumns());
        }
        if (other.getHorizontalColumns() != 0) {
          setHorizontalColumns(other.getHorizontalColumns());
        }
        if (other.getVerticalLines() != com.google.protobuf.ByteString.EMPTY) {
          setVerticalLines(other.getVerticalLines());
        }
        if (other.getHorizontalLines() != com.google.protobuf.ByteString.EMPTY) {
          setHorizontalLines(other.getHorizontalLines());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dab.DotsAndBoxes.GameState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dab.DotsAndBoxes.GameState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int verticalColumns_ ;
      /**
       * <code>uint32 vertical_columns = 1;</code>
       * @return The verticalColumns.
       */
      @java.lang.Override
      public int getVerticalColumns() {
        return verticalColumns_;
      }
      /**
       * <code>uint32 vertical_columns = 1;</code>
       * @param value The verticalColumns to set.
       * @return This builder for chaining.
       */
      public Builder setVerticalColumns(int value) {
        
        verticalColumns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 vertical_columns = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVerticalColumns() {
        
        verticalColumns_ = 0;
        onChanged();
        return this;
      }

      private int horizontalColumns_ ;
      /**
       * <code>uint32 horizontal_columns = 2;</code>
       * @return The horizontalColumns.
       */
      @java.lang.Override
      public int getHorizontalColumns() {
        return horizontalColumns_;
      }
      /**
       * <code>uint32 horizontal_columns = 2;</code>
       * @param value The horizontalColumns to set.
       * @return This builder for chaining.
       */
      public Builder setHorizontalColumns(int value) {
        
        horizontalColumns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 horizontal_columns = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHorizontalColumns() {
        
        horizontalColumns_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString verticalLines_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes vertical_lines = 3;</code>
       * @return The verticalLines.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getVerticalLines() {
        return verticalLines_;
      }
      /**
       * <code>bytes vertical_lines = 3;</code>
       * @param value The verticalLines to set.
       * @return This builder for chaining.
       */
      public Builder setVerticalLines(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        verticalLines_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes vertical_lines = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVerticalLines() {
        
        verticalLines_ = getDefaultInstance().getVerticalLines();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString horizontalLines_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes horizontal_lines = 4;</code>
       * @return The horizontalLines.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getHorizontalLines() {
        return horizontalLines_;
      }
      /**
       * <code>bytes horizontal_lines = 4;</code>
       * @param value The horizontalLines to set.
       * @return This builder for chaining.
       */
      public Builder setHorizontalLines(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        horizontalLines_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes horizontal_lines = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHorizontalLines() {
        
        horizontalLines_ = getDefaultInstance().getHorizontalLines();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dab.GameState)
    }

    // @@protoc_insertion_point(class_scope:dab.GameState)
    private static final dab.DotsAndBoxes.GameState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dab.DotsAndBoxes.GameState();
    }

    public static dab.DotsAndBoxes.GameState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameState>
        PARSER = new com.google.protobuf.AbstractParser<GameState>() {
      @java.lang.Override
      public GameState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dab.DotsAndBoxes.GameState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dab_GameParameter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dab_GameParameter_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dab_GameTurn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dab_GameTurn_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dab_GameState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dab_GameState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024dots-and-boxes.proto\022\003dab\"Y\n\rGameParam" +
      "eter\022\"\n\032number_of_vertical_columns\030\001 \001(\r" +
      "\022$\n\034number_of_horizontal_columns\030\002 \001(\r\"G" +
      "\n\010GameTurn\022\020\n\010vertical\030\001 \001(\010\022\025\n\rtarget_c" +
      "olumn\030\002 \001(\r\022\022\n\ntarget_gap\030\003 \001(\r\"s\n\tGameS" +
      "tate\022\030\n\020vertical_columns\030\001 \001(\r\022\032\n\022horizo" +
      "ntal_columns\030\002 \001(\r\022\026\n\016vertical_lines\030\003 \001" +
      "(\014\022\030\n\020horizontal_lines\030\004 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dab_GameParameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dab_GameParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dab_GameParameter_descriptor,
        new java.lang.String[] { "NumberOfVerticalColumns", "NumberOfHorizontalColumns", });
    internal_static_dab_GameTurn_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dab_GameTurn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dab_GameTurn_descriptor,
        new java.lang.String[] { "Vertical", "TargetColumn", "TargetGap", });
    internal_static_dab_GameState_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dab_GameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dab_GameState_descriptor,
        new java.lang.String[] { "VerticalColumns", "HorizontalColumns", "VerticalLines", "HorizontalLines", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
