// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nim.proto

package nim;

public final class Nim {
  private Nim() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameParameterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nim.GameParameter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 number_of_columns = 1;</code>
     * @return The numberOfColumns.
     */
    int getNumberOfColumns();

    /**
     * <code>uint32 number_of_stones = 2;</code>
     * @return The numberOfStones.
     */
    int getNumberOfStones();
  }
  /**
   * Protobuf type {@code nim.GameParameter}
   */
  public static final class GameParameter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nim.GameParameter)
      GameParameterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameParameter.newBuilder() to construct.
    private GameParameter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameParameter() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameParameter();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameParameter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numberOfColumns_ = input.readUInt32();
              break;
            }
            case 16: {

              numberOfStones_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nim.Nim.internal_static_nim_GameParameter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nim.Nim.internal_static_nim_GameParameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nim.Nim.GameParameter.class, nim.Nim.GameParameter.Builder.class);
    }

    public static final int NUMBER_OF_COLUMNS_FIELD_NUMBER = 1;
    private int numberOfColumns_;
    /**
     * <code>uint32 number_of_columns = 1;</code>
     * @return The numberOfColumns.
     */
    @java.lang.Override
    public int getNumberOfColumns() {
      return numberOfColumns_;
    }

    public static final int NUMBER_OF_STONES_FIELD_NUMBER = 2;
    private int numberOfStones_;
    /**
     * <code>uint32 number_of_stones = 2;</code>
     * @return The numberOfStones.
     */
    @java.lang.Override
    public int getNumberOfStones() {
      return numberOfStones_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numberOfColumns_ != 0) {
        output.writeUInt32(1, numberOfColumns_);
      }
      if (numberOfStones_ != 0) {
        output.writeUInt32(2, numberOfStones_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numberOfColumns_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, numberOfColumns_);
      }
      if (numberOfStones_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, numberOfStones_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nim.Nim.GameParameter)) {
        return super.equals(obj);
      }
      nim.Nim.GameParameter other = (nim.Nim.GameParameter) obj;

      if (getNumberOfColumns()
          != other.getNumberOfColumns()) return false;
      if (getNumberOfStones()
          != other.getNumberOfStones()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_OF_COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfColumns();
      hash = (37 * hash) + NUMBER_OF_STONES_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfStones();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nim.Nim.GameParameter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameParameter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameParameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameParameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameParameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameParameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameParameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nim.Nim.GameParameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nim.Nim.GameParameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nim.Nim.GameParameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nim.Nim.GameParameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nim.Nim.GameParameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nim.Nim.GameParameter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nim.GameParameter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nim.GameParameter)
        nim.Nim.GameParameterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nim.Nim.internal_static_nim_GameParameter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nim.Nim.internal_static_nim_GameParameter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nim.Nim.GameParameter.class, nim.Nim.GameParameter.Builder.class);
      }

      // Construct using nim.Nim.GameParameter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numberOfColumns_ = 0;

        numberOfStones_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nim.Nim.internal_static_nim_GameParameter_descriptor;
      }

      @java.lang.Override
      public nim.Nim.GameParameter getDefaultInstanceForType() {
        return nim.Nim.GameParameter.getDefaultInstance();
      }

      @java.lang.Override
      public nim.Nim.GameParameter build() {
        nim.Nim.GameParameter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public nim.Nim.GameParameter buildPartial() {
        nim.Nim.GameParameter result = new nim.Nim.GameParameter(this);
        result.numberOfColumns_ = numberOfColumns_;
        result.numberOfStones_ = numberOfStones_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nim.Nim.GameParameter) {
          return mergeFrom((nim.Nim.GameParameter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nim.Nim.GameParameter other) {
        if (other == nim.Nim.GameParameter.getDefaultInstance()) return this;
        if (other.getNumberOfColumns() != 0) {
          setNumberOfColumns(other.getNumberOfColumns());
        }
        if (other.getNumberOfStones() != 0) {
          setNumberOfStones(other.getNumberOfStones());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nim.Nim.GameParameter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nim.Nim.GameParameter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numberOfColumns_ ;
      /**
       * <code>uint32 number_of_columns = 1;</code>
       * @return The numberOfColumns.
       */
      @java.lang.Override
      public int getNumberOfColumns() {
        return numberOfColumns_;
      }
      /**
       * <code>uint32 number_of_columns = 1;</code>
       * @param value The numberOfColumns to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfColumns(int value) {
        
        numberOfColumns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_of_columns = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfColumns() {
        
        numberOfColumns_ = 0;
        onChanged();
        return this;
      }

      private int numberOfStones_ ;
      /**
       * <code>uint32 number_of_stones = 2;</code>
       * @return The numberOfStones.
       */
      @java.lang.Override
      public int getNumberOfStones() {
        return numberOfStones_;
      }
      /**
       * <code>uint32 number_of_stones = 2;</code>
       * @param value The numberOfStones to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfStones(int value) {
        
        numberOfStones_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_of_stones = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfStones() {
        
        numberOfStones_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nim.GameParameter)
    }

    // @@protoc_insertion_point(class_scope:nim.GameParameter)
    private static final nim.Nim.GameParameter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nim.Nim.GameParameter();
    }

    public static nim.Nim.GameParameter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameParameter>
        PARSER = new com.google.protobuf.AbstractParser<GameParameter>() {
      @java.lang.Override
      public GameParameter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameParameter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameParameter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameParameter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public nim.Nim.GameParameter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameTurnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nim.GameTurn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 target_column = 1;</code>
     * @return The targetColumn.
     */
    int getTargetColumn();

    /**
     * <code>uint32 number_to_take = 2;</code>
     * @return The numberToTake.
     */
    int getNumberToTake();
  }
  /**
   * Protobuf type {@code nim.GameTurn}
   */
  public static final class GameTurn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nim.GameTurn)
      GameTurnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameTurn.newBuilder() to construct.
    private GameTurn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameTurn() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameTurn();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameTurn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              targetColumn_ = input.readUInt32();
              break;
            }
            case 16: {

              numberToTake_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nim.Nim.internal_static_nim_GameTurn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nim.Nim.internal_static_nim_GameTurn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nim.Nim.GameTurn.class, nim.Nim.GameTurn.Builder.class);
    }

    public static final int TARGET_COLUMN_FIELD_NUMBER = 1;
    private int targetColumn_;
    /**
     * <code>uint32 target_column = 1;</code>
     * @return The targetColumn.
     */
    @java.lang.Override
    public int getTargetColumn() {
      return targetColumn_;
    }

    public static final int NUMBER_TO_TAKE_FIELD_NUMBER = 2;
    private int numberToTake_;
    /**
     * <code>uint32 number_to_take = 2;</code>
     * @return The numberToTake.
     */
    @java.lang.Override
    public int getNumberToTake() {
      return numberToTake_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (targetColumn_ != 0) {
        output.writeUInt32(1, targetColumn_);
      }
      if (numberToTake_ != 0) {
        output.writeUInt32(2, numberToTake_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (targetColumn_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, targetColumn_);
      }
      if (numberToTake_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, numberToTake_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nim.Nim.GameTurn)) {
        return super.equals(obj);
      }
      nim.Nim.GameTurn other = (nim.Nim.GameTurn) obj;

      if (getTargetColumn()
          != other.getTargetColumn()) return false;
      if (getNumberToTake()
          != other.getNumberToTake()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGET_COLUMN_FIELD_NUMBER;
      hash = (53 * hash) + getTargetColumn();
      hash = (37 * hash) + NUMBER_TO_TAKE_FIELD_NUMBER;
      hash = (53 * hash) + getNumberToTake();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nim.Nim.GameTurn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameTurn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameTurn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameTurn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameTurn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameTurn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameTurn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nim.Nim.GameTurn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nim.Nim.GameTurn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nim.Nim.GameTurn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nim.Nim.GameTurn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nim.Nim.GameTurn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nim.Nim.GameTurn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nim.GameTurn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nim.GameTurn)
        nim.Nim.GameTurnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nim.Nim.internal_static_nim_GameTurn_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nim.Nim.internal_static_nim_GameTurn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nim.Nim.GameTurn.class, nim.Nim.GameTurn.Builder.class);
      }

      // Construct using nim.Nim.GameTurn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        targetColumn_ = 0;

        numberToTake_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nim.Nim.internal_static_nim_GameTurn_descriptor;
      }

      @java.lang.Override
      public nim.Nim.GameTurn getDefaultInstanceForType() {
        return nim.Nim.GameTurn.getDefaultInstance();
      }

      @java.lang.Override
      public nim.Nim.GameTurn build() {
        nim.Nim.GameTurn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public nim.Nim.GameTurn buildPartial() {
        nim.Nim.GameTurn result = new nim.Nim.GameTurn(this);
        result.targetColumn_ = targetColumn_;
        result.numberToTake_ = numberToTake_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nim.Nim.GameTurn) {
          return mergeFrom((nim.Nim.GameTurn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nim.Nim.GameTurn other) {
        if (other == nim.Nim.GameTurn.getDefaultInstance()) return this;
        if (other.getTargetColumn() != 0) {
          setTargetColumn(other.getTargetColumn());
        }
        if (other.getNumberToTake() != 0) {
          setNumberToTake(other.getNumberToTake());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nim.Nim.GameTurn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nim.Nim.GameTurn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int targetColumn_ ;
      /**
       * <code>uint32 target_column = 1;</code>
       * @return The targetColumn.
       */
      @java.lang.Override
      public int getTargetColumn() {
        return targetColumn_;
      }
      /**
       * <code>uint32 target_column = 1;</code>
       * @param value The targetColumn to set.
       * @return This builder for chaining.
       */
      public Builder setTargetColumn(int value) {
        
        targetColumn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 target_column = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetColumn() {
        
        targetColumn_ = 0;
        onChanged();
        return this;
      }

      private int numberToTake_ ;
      /**
       * <code>uint32 number_to_take = 2;</code>
       * @return The numberToTake.
       */
      @java.lang.Override
      public int getNumberToTake() {
        return numberToTake_;
      }
      /**
       * <code>uint32 number_to_take = 2;</code>
       * @param value The numberToTake to set.
       * @return This builder for chaining.
       */
      public Builder setNumberToTake(int value) {
        
        numberToTake_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_to_take = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberToTake() {
        
        numberToTake_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nim.GameTurn)
    }

    // @@protoc_insertion_point(class_scope:nim.GameTurn)
    private static final nim.Nim.GameTurn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nim.Nim.GameTurn();
    }

    public static nim.Nim.GameTurn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameTurn>
        PARSER = new com.google.protobuf.AbstractParser<GameTurn>() {
      @java.lang.Override
      public GameTurn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameTurn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameTurn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameTurn> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public nim.Nim.GameTurn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nim.GameState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * height of columns, whitespace separated
     * </pre>
     *
     * <code>string columns = 1;</code>
     * @return The columns.
     */
    java.lang.String getColumns();
    /**
     * <pre>
     * height of columns, whitespace separated
     * </pre>
     *
     * <code>string columns = 1;</code>
     * @return The bytes for columns.
     */
    com.google.protobuf.ByteString
        getColumnsBytes();
  }
  /**
   * Protobuf type {@code nim.GameState}
   */
  public static final class GameState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nim.GameState)
      GameStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameState.newBuilder() to construct.
    private GameState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameState() {
      columns_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              columns_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nim.Nim.internal_static_nim_GameState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nim.Nim.internal_static_nim_GameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nim.Nim.GameState.class, nim.Nim.GameState.Builder.class);
    }

    public static final int COLUMNS_FIELD_NUMBER = 1;
    private volatile java.lang.Object columns_;
    /**
     * <pre>
     * height of columns, whitespace separated
     * </pre>
     *
     * <code>string columns = 1;</code>
     * @return The columns.
     */
    @java.lang.Override
    public java.lang.String getColumns() {
      java.lang.Object ref = columns_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        columns_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * height of columns, whitespace separated
     * </pre>
     *
     * <code>string columns = 1;</code>
     * @return The bytes for columns.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getColumnsBytes() {
      java.lang.Object ref = columns_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        columns_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getColumnsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, columns_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getColumnsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, columns_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nim.Nim.GameState)) {
        return super.equals(obj);
      }
      nim.Nim.GameState other = (nim.Nim.GameState) obj;

      if (!getColumns()
          .equals(other.getColumns())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumns().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nim.Nim.GameState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nim.Nim.GameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nim.Nim.GameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nim.Nim.GameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nim.Nim.GameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nim.Nim.GameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nim.Nim.GameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nim.Nim.GameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nim.Nim.GameState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nim.GameState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nim.GameState)
        nim.Nim.GameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nim.Nim.internal_static_nim_GameState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nim.Nim.internal_static_nim_GameState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nim.Nim.GameState.class, nim.Nim.GameState.Builder.class);
      }

      // Construct using nim.Nim.GameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        columns_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nim.Nim.internal_static_nim_GameState_descriptor;
      }

      @java.lang.Override
      public nim.Nim.GameState getDefaultInstanceForType() {
        return nim.Nim.GameState.getDefaultInstance();
      }

      @java.lang.Override
      public nim.Nim.GameState build() {
        nim.Nim.GameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public nim.Nim.GameState buildPartial() {
        nim.Nim.GameState result = new nim.Nim.GameState(this);
        result.columns_ = columns_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nim.Nim.GameState) {
          return mergeFrom((nim.Nim.GameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nim.Nim.GameState other) {
        if (other == nim.Nim.GameState.getDefaultInstance()) return this;
        if (!other.getColumns().isEmpty()) {
          columns_ = other.columns_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nim.Nim.GameState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nim.Nim.GameState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object columns_ = "";
      /**
       * <pre>
       * height of columns, whitespace separated
       * </pre>
       *
       * <code>string columns = 1;</code>
       * @return The columns.
       */
      public java.lang.String getColumns() {
        java.lang.Object ref = columns_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          columns_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * height of columns, whitespace separated
       * </pre>
       *
       * <code>string columns = 1;</code>
       * @return The bytes for columns.
       */
      public com.google.protobuf.ByteString
          getColumnsBytes() {
        java.lang.Object ref = columns_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          columns_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * height of columns, whitespace separated
       * </pre>
       *
       * <code>string columns = 1;</code>
       * @param value The columns to set.
       * @return This builder for chaining.
       */
      public Builder setColumns(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        columns_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * height of columns, whitespace separated
       * </pre>
       *
       * <code>string columns = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearColumns() {
        
        columns_ = getDefaultInstance().getColumns();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * height of columns, whitespace separated
       * </pre>
       *
       * <code>string columns = 1;</code>
       * @param value The bytes for columns to set.
       * @return This builder for chaining.
       */
      public Builder setColumnsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        columns_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nim.GameState)
    }

    // @@protoc_insertion_point(class_scope:nim.GameState)
    private static final nim.Nim.GameState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nim.Nim.GameState();
    }

    public static nim.Nim.GameState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameState>
        PARSER = new com.google.protobuf.AbstractParser<GameState>() {
      @java.lang.Override
      public GameState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public nim.Nim.GameState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nim_GameParameter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nim_GameParameter_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nim_GameTurn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nim_GameTurn_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nim_GameState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nim_GameState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tnim.proto\022\003nim\"D\n\rGameParameter\022\031\n\021num" +
      "ber_of_columns\030\001 \001(\r\022\030\n\020number_of_stones" +
      "\030\002 \001(\r\"9\n\010GameTurn\022\025\n\rtarget_column\030\001 \001(" +
      "\r\022\026\n\016number_to_take\030\002 \001(\r\"\034\n\tGameState\022\017" +
      "\n\007columns\030\001 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nim_GameParameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nim_GameParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nim_GameParameter_descriptor,
        new java.lang.String[] { "NumberOfColumns", "NumberOfStones", });
    internal_static_nim_GameTurn_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nim_GameTurn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nim_GameTurn_descriptor,
        new java.lang.String[] { "TargetColumn", "NumberToTake", });
    internal_static_nim_GameState_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nim_GameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nim_GameState_descriptor,
        new java.lang.String[] { "Columns", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
